import { type Project, type Developer } from './types';

export const DEVELOPERS: Developer[] = [
  {
    id: 'DEV0010',
    name: 'Rahul Khan',
    initials: 'RK',
    status: 'Ready',
    education: 'M.S. Computer Science',
    experience: '4 Years Experience',
    skills: ["ARIMA", "Azure", "CI/CD", "Computer Vision", "Django", "FastAPI", "LangChain", "MLOps", "SQL", "Snowflake", "Transformers", "Vector DBs", "XGBoost", "YOLO"],
    domainPreference: "E-commerce, HealthTech",
    pastProjects: ["Anomaly Detection for SaaS"],
    role: 'MLOps Engineer',
    level: 'Mid',
    location: 'Delhi NCR',
    workPreference: 'Remote',
    hourlyRate: 36.0,
    availability: '4 weeks',
  },
  {
    id: 'DEV0006',
    name: 'Rahul Kapoor',
    initials: 'RK',
    status: 'Ready',
    education: 'B.Tech Information Technology',
    experience: '7 Years Experience',
    skills: ["FAISS", "FastAPI", "LightGBM", "Prompt Engineering", "Redis", "Spark", "Vector DBs", "XGBoost", "scikit-learn"],
    domainPreference: "Cybersecurity, EdTech",
    pastProjects: ["Computer Vision QA for Media"],
    role: 'ML Engineer',
    level: 'Mid',
    location: 'Delhi NCR',
    workPreference: 'Remote',
    hourlyRate: 48.0,
    availability: '1 week',
  },
  {
    id: 'DEV0008',
    name: 'Aisha Mehta',
    initials: 'AM',
    status: 'Ready',
    education: 'M.Sc. Data Science',
    experience: '5 Years Experience',
    skills: ["Airflow", "Azure", "LLMs", "MLOps", "Snowflake", "Time Series", "XGBoost"],
    domainPreference: "E-commerce, Gaming",
    pastProjects: ["Computer Vision QA for ClimateTech"],
    role: 'NLP Engineer',
    level: 'Mid',
    location: 'Bengaluru',
    workPreference: 'Remote',
    hourlyRate: 41.0,
    availability: '1 week',
  },
  {
    id: 'DEV0011',
    name: 'Rahul Singh',
    initials: 'RS',
    status: 'Ready',
    education: 'B.E. Computer Engineering',
    experience: '7 Years Experience',
    skills: ["AWS", "CI/CD", "Computer Vision", "Django", "FastAPI", "GCP", "OpenAI API", "PostgreSQL", "Prophet", "Python", "Statistics", "dbt", "scikit-learn"],
    domainPreference: "ClimateTech",
    pastProjects: ["Computer Vision QA for SaaS"],
    role: 'Backend Engineer',
    level: 'Mid',
    location: 'Bengaluru',
    workPreference: 'Hybrid',
    hourlyRate: 50.0,
    availability: '2 weeks',
  },
  {
    id: 'DEV0024',
    name: 'Aditya Nair',
    initials: 'AN',
    status: 'Ready',
    education: 'B.Tech Computer Science',
    experience: '3 Years Experience',
    skills: ["A/B Testing", "Azure", "Data Modeling", "FAISS", "OpenAI API", "RAG"],
    domainPreference: "Cybersecurity, Media",
    pastProjects: ["MLOps Platform for HealthTech"],
    role: 'ML Engineer',
    level: 'Mid',
    location: 'Ahmedabad',
    workPreference: 'Remote',
    hourlyRate: 42.0,
    availability: '6 weeks',
  },
  {
    id: 'DEV0046',
    name: 'Siddharth Chatterjee',
    initials: 'SC',
    status: 'Ready',
    education: 'M.Tech AI/ML',
    experience: '3 Years Experience',
    skills: ["Computer Vision", "Django", "FAISS", "PostgreSQL", "TensorFlow", "Time Series", "Vector DBs", "YOLO"],
    domainPreference: "Cybersecurity, EdTech",
    pastProjects: ["Computer Vision QA for Media"],
    role: 'NLP Engineer',
    level: 'Mid',
    location: 'Kolkata',
    workPreference: 'Remote',
    hourlyRate: 36.0,
    availability: '4 weeks',
  },
  {
    id: 'DEV0041',
    name: 'Ishaan Mehta',
    initials: 'IM',
    status: 'Ready',
    education: 'B.Tech Computer Science',
    experience: '4 Years Experience',
    skills: ["ARIMA", "AWS", "CI/CD", "Data Modeling", "GCP", "Kubernetes", "LLMs", "OpenCV", "PostgreSQL", "Redis", "Statistics", "Weaviate", "YOLO", "dbt"],
    domainPreference: "E-commerce, Logistics, Media",
    pastProjects: ["Computer Vision QA for ClimateTech", "Churn Prediction for ClimateTech", "MLOps Platform for HealthTech"],
    role: 'Full-Stack Engineer',
    level: 'Mid',
    location: 'Hyderabad',
    workPreference: 'Hybrid',
    hourlyRate: 43.0,
    availability: 'Immediate',
  },
  {
    id: 'DEV0027',
    name: 'Aisha Kapoor',
    initials: 'AK',
    status: 'Ready',
    education: 'PhD in Computer Science',
    experience: '10 Years Experience',
    skills: ["Data Modeling", "FastAPI", "Great Expectations", "Kubernetes", "LightGBM", "MLOps", "MLflow", "NLP", "OpenCV", "Pandas", "Redis", "Spark", "Vector DBs"],
    domainPreference: "E-commerce",
    pastProjects: ["Fraud Detection for HealthTech", "Search Relevance for FinTech"],
    role: 'Full-Stack Engineer',
    level: 'Senior',
    location: 'Mumbai',
    workPreference: 'Remote',
    hourlyRate: 41.0,
    availability: 'Immediate',
  },
  {
    id: 'DEV0048',
    name: 'Kavya Patel',
    initials: 'KP',
    status: 'Ready',
    education: 'B.Sc. Computer Science',
    experience: '1 Year Experience',
    skills: ["ARIMA", "AWS", "Computer Vision", "FastAPI", "Great Expectations", "Prompt Engineering", "SQL", "XGBoost"],
    domainPreference: "EdTech, Logistics",
    pastProjects: ["Marketing Experimentation for SaaS"],
    role: 'Data Scientist',
    level: 'Junior',
    location: 'Chennai',
    workPreference: 'Remote',
    hourlyRate: 21.0,
    availability: '1 week',
  },
  {
    id: 'DEV0040',
    name: 'Vihaan Das',
    initials: 'VD',
    status: 'Ready',
    education: 'B.Tech Information Technology',
    experience: '3 Years Experience',
    skills: ["A/B Testing", "BERT", "CI/CD", "Data Modeling", "Django", "FastAPI", "Great Expectations", "Kubernetes", "LangChain", "Time Series"],
    domainPreference: "Cybersecurity, SaaS",
    pastProjects: ["Demand Forecasting for FinTech"],
    role: 'Data Scientist',
    level: 'Junior',
    location: 'Hyderabad',
    workPreference: 'Hybrid',
    hourlyRate: 28.0,
    availability: '1 week',
  },
  {
    id: 'DEV0033',
    name: 'Riya Das',
    initials: 'RD',
    status: 'Ready',
    education: 'M.S. Software Systems',
    experience: '9 Years Experience',
    skills: ["Airflow", "Azure", "Kafka", "LangChain", "LightGBM", "OpenAI API", "PostgreSQL", "Prophet", "Python", "Redis", "XGBoost", "dbt", "scikit-learn"],
    domainPreference: "E-commerce, FinTech, HealthTech",
    pastProjects: ["Demand Forecasting for HealthTech", "MLOps Platform for HealthTech"],
    role: 'NLP Engineer',
    level: 'Senior',
    location: 'Ahmedabad',
    workPreference: 'Remote',
    hourlyRate: 55.0,
    availability: '2 weeks',
  },
  {
    id: 'DEV0050',
    name: 'Diya Khan',
    initials: 'DK',
    status: 'Ready',
    education: 'M.Sc. Statistics',
    experience: '4 Years Experience',
    skills: ["Airflow", "BERT", "Computer Vision", "Elasticsearch", "Great Expectations", "LLMs", "LightGBM", "MLOps", "NLP", "Terraform", "XGBoost", "dbt"],
    domainPreference: "ClimateTech, Media",
    pastProjects: ["ETL Modernization for Cybersecurity", "Anomaly Detection for SaaS"],
    role: 'Computer Vision Engineer',
    level: 'Mid',
    location: 'Ahmedabad',
    workPreference: 'Remote',
    hourlyRate: 45.0,
    availability: '8 weeks',
  },
  {
    id: 'DEV0002',
    name: 'Ananya Sharma',
    initials: 'AS',
    status: 'Ready',
    education: 'PhD in Data Science',
    experience: '10 Years Experience',
    skills: ["CI/CD", "Great Expectations", "Kafka", "LangChain", "PostgreSQL", "Prompt Engineering", "Python", "TensorFlow", "Weaviate", "scikit-learn"],
    domainPreference: "Cybersecurity, EdTech, FinTech",
    pastProjects: ["Demand Forecasting for FinTech"],
    role: 'NLP Engineer',
    level: 'Senior',
    location: 'Chennai',
    workPreference: 'Hybrid',
    hourlyRate: 47.0,
    availability: '2 weeks',
  },
  {
    id: 'DEV0034',
    name: 'Ananya Bose',
    initials: 'AB',
    status: 'Ready',
    education: 'B.Tech Computer Science',
    experience: '4 Years Experience',
    skills: ["Azure", "Docker", "OpenCV", "PostgreSQL", "Redis", "scikit-learn"],
    domainPreference: "FinTech",
    pastProjects: ["Computer Vision QA for SaaS", "ETL Modernization for ClimateTech"],
    role: 'NLP Engineer',
    level: 'Mid',
    location: 'Bengaluru',
    workPreference: 'Remote',
    hourlyRate: 28.0,
    availability: 'Immediate',
  },
  {
    id: 'DEV0039',
    name: 'Isha Bose',
    initials: 'IB',
    status: 'Ready',
    education: 'B.Sc. IT',
    experience: '3 Years Experience',
    skills: ["ARIMA", "CI/CD", "FastAPI", "LLMs", "MLOps", "PyTorch", "SQL", "Statistics", "Terraform", "Vector DBs", "XGBoost"],
    domainPreference: "Cybersecurity, E-commerce",
    pastProjects: ["Demand Forecasting for HealthTech"],
    role: 'Data Engineer',
    level: 'Junior',
    location: 'Hyderabad',
    workPreference: 'Remote',
    hourlyRate: 18.0,
    availability: 'Immediate',
  },
  {
    id: 'DEV0049',
    name: 'Kunal Patel',
    initials: 'KP',
    status: 'Ready',
    education: 'B.E. Electronics',
    experience: '5 Years Experience',
    skills: ["Airflow", "BERT", "Docker", "Elasticsearch", "FAISS", "MLflow", "Pinecone", "PostgreSQL", "TensorFlow", "Terraform"],
    domainPreference: "ClimateTech",
    pastProjects: ["Demand Forecasting for FinTech", "Marketing Experimentation for SaaS", "MLOps Platform for HealthTech"],
    role: 'Backend Engineer',
    level: 'Mid',
    location: 'Pune',
    workPreference: 'Onsite',
    hourlyRate: 36.0,
    availability: 'Immediate',
  },
  {
    id: 'DEV0015',
    name: 'Aisha Gupta',
    initials: 'AG',
    status: 'Ready',
    education: 'B.Tech Computer Science',
    experience: '1 Year Experience',
    skills: ["AWS", "Data Modeling", "Django", "Prophet", "TensorFlow", "scikit-learn"],
    domainPreference: "Gaming",
    pastProjects: ["Fraud Detection for E-commerce"],
    role: 'Computer Vision Engineer',
    level: 'Junior',
    location: 'Delhi NCR',
    workPreference: 'Remote',
    hourlyRate: 30.0,
    availability: '6 weeks',
  },
  {
    id: 'DEV0019',
    name: 'Priya Gupta',
    initials: 'PG',
    status: 'Ready',
    education: 'M.Tech AI',
    experience: '12 Years Experience',
    skills: ["AWS", "Airflow", "Azure", "CI/CD", "Data Modeling", "Docker", "NLP", "NumPy", "Pinecone", "Prompt Engineering", "Redis", "SQL", "dbt"],
    domainPreference: "FinTech, Logistics",
    pastProjects: ["Demand Forecasting for HealthTech"],
    role: 'NLP Engineer',
    level: 'Senior',
    location: 'Delhi NCR',
    workPreference: 'Hybrid',
    hourlyRate: 44.0,
    availability: 'Immediate',
  },
  {
    id: 'DEV0004',
    name: 'Aisha Singh',
    initials: 'AS',
    status: 'Ready',
    education: 'B.Tech Computer Science',
    experience: '10 Years Experience',
    skills: ["ARIMA", "Airflow", "Docker", "FastAPI", "Great Expectations", "LightGBM", "MLOps", "NLP", "OpenCV", "Python", "dbt"],
    domainPreference: "ClimateTech, FinTech, Logistics",
    pastProjects: ["Marketing Experimentation for SaaS"],
    role: 'Backend Engineer',
    level: 'Senior',
    location: 'Pune',
    workPreference: 'Hybrid',
    hourlyRate: 49.0,
    availability: '3 weeks',
  },
  {
    id: 'DEV0016',
    name: 'Neha Chatterjee',
    initials: 'NC',
    status: 'Ready',
    education: 'M.Sc. Computer Science',
    experience: '1 Year Experience',
    skills: ["A/B Testing", "ARIMA", "AWS", "Azure", "BERT", "Elasticsearch", "GCP", "LangChain", "MLflow", "Spark", "Statistics", "TensorFlow", "Weaviate", "XGBoost"],
    domainPreference: "Cybersecurity, E-commerce, SaaS",
    pastProjects: ["ETL Modernization for ClimateTech"],
    role: 'MLOps Engineer',
    level: 'Junior',
    location: 'Kolkata',
    workPreference: 'Hybrid',
    hourlyRate: 26.0,
    availability: 'Immediate',
  },
];

export const PROJECTS: Project[] = [
  {
    id: 'PRJ0018',
    title: 'Anomaly Detection for SaaS',
    description: 'Implementing an anomaly detection system for SaaS platforms using Computer Vision and FastAPI.',
    matchScore: 0,
    domain: 'SaaS',
    domainIcon: 'Cloud',
    difficulty: 'Intermediate',
    estTime: '12 weeks',
    skillGap: [],
    reasoning: '',
    recommendations: [],
    confidence: 'Low',
    experienceEvaluation: 'Intermediate',
    domainAlignment: 'Weak',
    accentColor: 'primary',
    projectType: 'Anomaly Detection',
    seniorityRequired: 'Mid',
    minYearsExperience: 5,
    complexity: 'Medium',
    budgetPerHour: 52.0,
    remoteOk: false,
    requiredSkills: ['Computer Vision', 'FastAPI', 'Great Expectations', 'Kubernetes', 'OpenAI API', 'SQL', 'dbt'],
  },
  {
    id: 'PRJ0017',
    title: 'Computer Vision QA for Media',
    description: 'Automating quality assurance in media using computer vision and deep learning.',
    matchScore: 0,
    domain: 'Media',
    domainIcon: 'Play',
    difficulty: 'Expert',
    estTime: '25 weeks',
    skillGap: [],
    reasoning: '',
    recommendations: [],
    confidence: 'Low',
    experienceEvaluation: 'Expert',
    domainAlignment: 'Weak',
    accentColor: 'secondary',
    projectType: 'Computer Vision QA',
    seniorityRequired: 'Senior',
    minYearsExperience: 10,
    complexity: 'Low',
    budgetPerHour: 44.0,
    remoteOk: true,
    requiredSkills: ['Computer Vision', 'Deep Learning', 'PyTorch', 'SQL'],
  },
  {
    id: 'PRJ0020',
    title: 'Computer Vision QA for ClimateTech',
    description: 'Automating quality assurance in ClimateTech using computer vision and deep learning.',
    matchScore: 0,
    domain: 'ClimateTech',
    domainIcon: 'Leaf',
    difficulty: 'Expert',
    estTime: '13 weeks',
    skillGap: [],
    reasoning: '',
    recommendations: [],
    confidence: 'Low',
    experienceEvaluation: 'Expert',
    domainAlignment: 'Weak',
    accentColor: 'primary',
    projectType: 'Computer Vision QA',
    seniorityRequired: 'Senior',
    minYearsExperience: 6,
    complexity: 'Medium',
    budgetPerHour: 49.0,
    remoteOk: true,
    requiredSkills: ['Computer Vision', 'Deep Learning', 'PyTorch', 'SQL'],
  },
  {
    id: 'PRJ0009',
    title: 'Computer Vision QA for SaaS',
    description: 'Automating quality assurance in SaaS using computer vision and deep learning.',
    matchScore: 0,
    domain: 'SaaS',
    domainIcon: 'Cloud',
    difficulty: 'Expert',
    estTime: '13 weeks',
    skillGap: [],
    reasoning: '',
    recommendations: [],
    confidence: 'Low',
    experienceEvaluation: 'Expert',
    domainAlignment: 'Weak',
    accentColor: 'primary',
    projectType: 'Computer Vision QA',
    seniorityRequired: 'Senior',
    minYearsExperience: 7,
    complexity: 'Medium',
    budgetPerHour: 63.0,
    remoteOk: true,
    requiredSkills: ['Computer Vision', 'Deep Learning', 'PyTorch', 'SQL'],
  },
  {
    id: 'PRJ0019',
    title: 'MLOps Platform for HealthTech',
    description: 'Designing and implementing a robust MLOps platform for health technology.',
    matchScore: 0,
    domain: 'HealthTech',
    domainIcon: 'Activity',
    difficulty: 'Beginner',
    estTime: '6 weeks',
    skillGap: [],
    reasoning: '',
    recommendations: [],
    confidence: 'Low',
    experienceEvaluation: 'Beginner',
    domainAlignment: 'Weak',
    accentColor: 'secondary',
    projectType: 'MLOps Platform',
    seniorityRequired: 'Junior',
    minYearsExperience: 1,
    complexity: 'Low',
    budgetPerHour: 43.0,
    remoteOk: true,
    requiredSkills: ['Docker', 'Kubernetes', 'MLflow', 'Python', 'SQL'],
  },
  {
    id: 'PRJ0010',
    title: 'Fraud Detection for HealthTech',
    description: 'Implementing machine learning models to detect fraudulent activities in health technology.',
    matchScore: 0,
    domain: 'HealthTech',
    domainIcon: 'Activity',
    difficulty: 'Expert',
    estTime: '12 weeks',
    skillGap: [],
    reasoning: '',
    recommendations: [],
    confidence: 'Low',
    experienceEvaluation: 'Expert',
    domainAlignment: 'Weak',
    accentColor: 'primary',
    projectType: 'Fraud Detection',
    seniorityRequired: 'Senior',
    minYearsExperience: 7,
    complexity: 'Medium',
    budgetPerHour: 45.0,
    remoteOk: true,
    requiredSkills: ['Python', 'Scikit-learn', 'SQL', 'XGBoost'],
  },
  {
    id: 'PRJ0008',
    title: 'Marketing Experimentation for SaaS',
    description: 'Running A/B tests and marketing experiments for SaaS platforms.',
    matchScore: 0,
    domain: 'SaaS',
    domainIcon: 'Cloud',
    difficulty: 'Intermediate',
    estTime: '18 weeks',
    skillGap: [],
    reasoning: '',
    recommendations: [],
    confidence: 'Low',
    experienceEvaluation: 'Intermediate',
    domainAlignment: 'Weak',
    accentColor: 'primary',
    projectType: 'Marketing Experimentation',
    seniorityRequired: 'Mid',
    minYearsExperience: 6,
    complexity: 'Medium',
    budgetPerHour: 63.0,
    remoteOk: false,
    requiredSkills: ['A/B Testing', 'Python', 'SQL', 'Statistics'],
  },
  {
    id: 'PRJ0012',
    title: 'Demand Forecasting for FinTech',
    description: 'Predicting future demand for financial services using time series analysis.',
    matchScore: 0,
    domain: 'FinTech',
    domainIcon: 'DollarSign',
    difficulty: 'Expert',
    estTime: '21 weeks',
    skillGap: [],
    reasoning: '',
    recommendations: [],
    confidence: 'Low',
    experienceEvaluation: 'Expert',
    domainAlignment: 'Weak',
    accentColor: 'secondary',
    projectType: 'Demand Forecasting',
    seniorityRequired: 'Senior',
    minYearsExperience: 10,
    complexity: 'Low',
    budgetPerHour: 50.0,
    remoteOk: true,
    requiredSkills: ['Python', 'SQL', 'Time Series', 'XGBoost'],
  },
  {
    id: 'PRJ0007',
    title: 'Demand Forecasting for HealthTech',
    description: 'Predicting future demand for health services using time series analysis.',
    matchScore: 0,
    domain: 'HealthTech',
    domainIcon: 'Activity',
    difficulty: 'Expert',
    estTime: '20 weeks',
    skillGap: [],
    reasoning: '',
    recommendations: [],
    confidence: 'Low',
    experienceEvaluation: 'Expert',
    domainAlignment: 'Weak',
    accentColor: 'secondary',
    projectType: 'Demand Forecasting',
    seniorityRequired: 'Senior',
    minYearsExperience: 9,
    complexity: 'Low',
    budgetPerHour: 52.0,
    remoteOk: true,
    requiredSkills: ['Python', 'SQL', 'Time Series', 'XGBoost'],
  },
  {
    id: 'PRJ0003',
    title: 'ETL Modernization for Cybersecurity',
    description: 'Modernizing data pipelines for cybersecurity analytics.',
    matchScore: 0,
    domain: 'Cybersecurity',
    domainIcon: 'Shield',
    difficulty: 'Expert',
    estTime: '13 weeks',
    skillGap: [],
    reasoning: '',
    recommendations: [],
    confidence: 'Low',
    experienceEvaluation: 'Expert',
    domainAlignment: 'Weak',
    accentColor: 'primary',
    projectType: 'ETL Modernization',
    seniorityRequired: 'Senior',
    minYearsExperience: 6,
    complexity: 'Medium',
    budgetPerHour: 37.0,
    remoteOk: true,
    requiredSkills: ['Airflow', 'Python', 'SQL', 'dbt'],
  },
  {
    id: 'PRJ0013',
    title: 'Churn Prediction for ClimateTech',
    description: 'Analyzing user behavior to predict and prevent churn in ClimateTech services.',
    matchScore: 0,
    domain: 'ClimateTech',
    domainIcon: 'Leaf',
    difficulty: 'Expert',
    estTime: '27 weeks',
    skillGap: [],
    reasoning: '',
    recommendations: [],
    confidence: 'Low',
    experienceEvaluation: 'Expert',
    domainAlignment: 'Weak',
    accentColor: 'primary',
    projectType: 'Churn Prediction',
    seniorityRequired: 'Senior',
    minYearsExperience: 6,
    complexity: 'Medium',
    budgetPerHour: 47.0,
    remoteOk: true,
    requiredSkills: ['Python', 'Scikit-learn', 'SQL', 'XGBoost'],
  },
  {
    id: 'PRJ0014',
    title: 'Fraud Detection for E-commerce',
    description: 'Implementing machine learning models to detect fraudulent activities in E-commerce.',
    matchScore: 0,
    domain: 'E-commerce',
    domainIcon: 'ShoppingCart',
    difficulty: 'Intermediate',
    estTime: '26 weeks',
    skillGap: [],
    reasoning: '',
    recommendations: [],
    confidence: 'Low',
    experienceEvaluation: 'Intermediate',
    domainAlignment: 'Weak',
    accentColor: 'red-500',
    projectType: 'Fraud Detection',
    seniorityRequired: 'Mid',
    minYearsExperience: 6,
    complexity: 'High',
    budgetPerHour: 55.0,
    remoteOk: true,
    requiredSkills: ['Python', 'Scikit-learn', 'SQL', 'XGBoost'],
  },
  {
    id: 'PRJ0004',
    title: 'ETL Modernization for ClimateTech',
    description: 'Modernizing data pipelines for ClimateTech analytics.',
    matchScore: 0,
    domain: 'ClimateTech',
    domainIcon: 'Leaf',
    difficulty: 'Expert',
    estTime: '20 weeks',
    skillGap: [],
    reasoning: '',
    recommendations: [],
    confidence: 'Low',
    experienceEvaluation: 'Expert',
    domainAlignment: 'Weak',
    accentColor: 'red-500',
    projectType: 'ETL Modernization',
    seniorityRequired: 'Senior',
    minYearsExperience: 9,
    complexity: 'High',
    budgetPerHour: 98.0,
    remoteOk: true,
    requiredSkills: ['Airflow', 'Python', 'SQL', 'dbt'],
  },
  {
    id: 'PRJ0001',
    title: 'ETL Modernization for Cybersecurity (Advanced)',
    description: 'Advanced modernization of data pipelines for cybersecurity analytics.',
    matchScore: 0,
    domain: 'Cybersecurity',
    domainIcon: 'Shield',
    difficulty: 'Expert',
    estTime: '8 weeks',
    skillGap: [],
    reasoning: '',
    recommendations: [],
    confidence: 'Low',
    experienceEvaluation: 'Expert',
    domainAlignment: 'Weak',
    accentColor: 'primary',
    projectType: 'ETL Modernization',
    seniorityRequired: 'Senior',
    minYearsExperience: 9,
    complexity: 'Medium',
    budgetPerHour: 42.0,
    remoteOk: true,
    requiredSkills: ['Airflow', 'Python', 'SQL', 'dbt'],
  },
  {
    id: 'PRJ0016',
    title: 'Computer Vision QA for HealthTech',
    description: 'Automating quality assurance in HealthTech using computer vision and deep learning.',
    matchScore: 0,
    domain: 'HealthTech',
    domainIcon: 'Activity',
    difficulty: 'Intermediate',
    estTime: '13 weeks',
    skillGap: [],
    reasoning: '',
    recommendations: [],
    confidence: 'Low',
    experienceEvaluation: 'Intermediate',
    domainAlignment: 'Weak',
    accentColor: 'secondary',
    projectType: 'Computer Vision QA',
    seniorityRequired: 'Mid',
    minYearsExperience: 6,
    complexity: 'Low',
    budgetPerHour: 30.0,
    remoteOk: true,
    requiredSkills: ['Computer Vision', 'Deep Learning', 'PyTorch', 'SQL'],
  },
  {
    id: 'PRJ0002',
    title: 'RAG Chatbot for EdTech',
    description: 'Developing a Retrieval-Augmented Generation chatbot for educational applications.',
    matchScore: 0,
    domain: 'EdTech',
    domainIcon: 'GraduationCap',
    difficulty: 'Intermediate',
    estTime: '14 weeks',
    skillGap: [],
    reasoning: '',
    recommendations: [],
    confidence: 'Low',
    experienceEvaluation: 'Intermediate',
    domainAlignment: 'Weak',
    accentColor: 'primary',
    projectType: 'RAG Chatbot',
    seniorityRequired: 'Mid',
    minYearsExperience: 5,
    complexity: 'Medium',
    budgetPerHour: 56.0,
    remoteOk: true,
    requiredSkills: ['LangChain', 'OpenAI API', 'Python', 'Vector DB'],
  },
  {
    id: 'PRJ0011',
    title: 'Marketing Experimentation for Logistics',
    description: 'Running A/B tests and marketing experiments for logistics platforms.',
    matchScore: 0,
    domain: 'Logistics',
    domainIcon: 'Truck',
    difficulty: 'Intermediate',
    estTime: '14 weeks',
    skillGap: [],
    reasoning: '',
    recommendations: [],
    confidence: 'Low',
    experienceEvaluation: 'Intermediate',
    domainAlignment: 'Weak',
    accentColor: 'red-500',
    projectType: 'Marketing Experimentation',
    seniorityRequired: 'Mid',
    minYearsExperience: 3,
    complexity: 'High',
    budgetPerHour: 67.0,
    remoteOk: true,
    requiredSkills: ['A/B Testing', 'Python', 'SQL', 'Statistics'],
  },
  {
    id: 'PRJ0015',
    title: 'ETL Modernization for Cybersecurity (Enterprise)',
    description: 'Enterprise-level modernization of data pipelines for cybersecurity analytics.',
    matchScore: 0,
    domain: 'Cybersecurity',
    domainIcon: 'Shield',
    difficulty: 'Intermediate',
    estTime: '24 weeks',
    skillGap: [],
    reasoning: '',
    recommendations: [],
    confidence: 'Low',
    experienceEvaluation: 'Intermediate',
    domainAlignment: 'Weak',
    accentColor: 'red-500',
    projectType: 'ETL Modernization',
    seniorityRequired: 'Mid',
    minYearsExperience: 3,
    complexity: 'High',
    budgetPerHour: 83.0,
    remoteOk: false,
    requiredSkills: ['Airflow', 'Python', 'SQL', 'dbt'],
  },
  {
    id: 'PRJ0005',
    title: 'RAG Chatbot for Cybersecurity',
    description: 'Developing a Retrieval-Augmented Generation chatbot for cybersecurity applications.',
    matchScore: 0,
    domain: 'Cybersecurity',
    domainIcon: 'Shield',
    difficulty: 'Intermediate',
    estTime: '19 weeks',
    skillGap: [],
    reasoning: '',
    recommendations: [],
    confidence: 'Low',
    experienceEvaluation: 'Intermediate',
    domainAlignment: 'Weak',
    accentColor: 'primary',
    projectType: 'RAG Chatbot',
    seniorityRequired: 'Mid',
    minYearsExperience: 6,
    complexity: 'Medium',
    budgetPerHour: 41.0,
    remoteOk: true,
    requiredSkills: ['LangChain', 'OpenAI API', 'Python', 'Vector DB'],
  },
  {
    id: 'PRJ0006',
    title: 'Search Relevance for FinTech',
    description: 'Improving search result relevance for financial technology applications.',
    matchScore: 0,
    domain: 'FinTech',
    domainIcon: 'DollarSign',
    difficulty: 'Expert',
    estTime: '13 weeks',
    skillGap: [],
    reasoning: '',
    recommendations: [],
    confidence: 'Low',
    experienceEvaluation: 'Expert',
    domainAlignment: 'Weak',
    accentColor: 'primary',
    projectType: 'Search Relevance',
    seniorityRequired: 'Senior',
    minYearsExperience: 8,
    complexity: 'Medium',
    budgetPerHour: 73.0,
    remoteOk: true,
    requiredSkills: ['Elasticsearch', 'Python', 'SQL'],
  },
];
